# Generated by Django 5.0.4 on 2024-04-14 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 4, 14)),
        ),
    ]
