# Generated by Django 5.0.4 on 2024-04-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_subscription_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='isSubscribed',
        ),
    ]
