# Generated by Django 5.0.4 on 2024-04-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_subscription_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
    ]
